// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdYdPYlixu1IOo3TsrwSqRQuaFmEBkLcc',
    appId: '1:424408147118:web:d9d204ca5f1c629429793f',
    messagingSenderId: '424408147118',
    projectId: 'ccook-22f61',
    authDomain: 'ccook-22f61.firebaseapp.com',
    storageBucket: 'ccook-22f61.appspot.com',
    measurementId: 'G-7B4YFQHEXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ9ajkXCDibN6lgAyCBQIGtlwjDpRTnNw',
    appId: '1:424408147118:android:7dcdc9d170b8016629793f',
    messagingSenderId: '424408147118',
    projectId: 'ccook-22f61',
    storageBucket: 'ccook-22f61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4264XuQw2nnDNzS93wCOyPD6FpeSrqOw',
    appId: '1:424408147118:ios:a6f5ca5384599e5729793f',
    messagingSenderId: '424408147118',
    projectId: 'ccook-22f61',
    storageBucket: 'ccook-22f61.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4264XuQw2nnDNzS93wCOyPD6FpeSrqOw',
    appId: '1:424408147118:ios:d523bd516c339f1329793f',
    messagingSenderId: '424408147118',
    projectId: 'ccook-22f61',
    storageBucket: 'ccook-22f61.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
